### ISSUE TITLE
Timeout during building consul image

### ISSUE THREAD

**Issue by yillkid** [nuriel77/iri-lb-haproxy#2]
#### Install iri-lb-haproxy by ansible-playbook:
`$ ansible-playbook -i inventory -v site.yml`

#### Error message:
```
fatal: [localhost]: FAILED! => {“changed”: false, “msg”: “Error connecting: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.”}
```

#### Log:
```TASK [consul : build consul image] *************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float."}
	to retry, use: --limit @/home/ubuntu/iri-lb-haproxy/site.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=21   changed=4    unreachable=0    failed=1```

**Comment by nuriel77** [comment]
Hi @yillkid 

Do you have some more output from the logs?
I'd like to know exactly at which task this failure occurred. The Consul image build task is in a block, I wonder in which of these tasks did it happen:

```
- name: check consul image exists
  shell: "/usr/bin/docker images {{ consul_image }}:{{ consul_tag }} | grep -q ^consul"
  register: consul_image_stat
  failed_when: "consul_image_stat.rc > 1"

- name: docker build consul image
  block:

    - name: create temporary build directory
      tempfile:
        state: directory
      register: tempdir

    - name: copy Dockerfile
      template:
        src: templates/Dockerfile.j2
        dest: "{{ tempdir.path }}/Dockerfile"

    - name: build consul image
      docker_image:
        path: "{{ tempdir.path }}"
        name: "{{ consul_image }}"
        tag: "{{ consul_tag }}"

    - name: remove temporary build dir
      file:
        state: absent
        path: "{{ tempdir.path }}"
  when: consul_image_stat.rc == 1
  tags:
    - docker_build
```

In addition, did you already have Docker installed on your node?
(I just tested a new install on Ubuntu 18.04 and it worked flawlessly)
